services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - ./local/localstack:/etc/localstack/init/ready.d
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  lowkey-vault:
    container_name: docker-compose-lowkey-vault
    image: nagyesta/lowkey-vault:3.0.6
    ports:
      - "8443:8443"
    volumes:
      - example-import:/import/:rw
      - example-config:/config/:ro
    environment:
      # Set arguments for Lowkey Vault configuring key parameters, such as:
      # - setting the port we want to use: --server.port=8443
      # - overriding the key store type: --server.ssl.key-store-type=JKS
      # - overriding the key store path: --server.ssl.key-store=/config/cert.jks
      # - overriding the key store password: --server.ssl.key-store-password=password
      # - disable automatic vault creation: --LOWKEY_VAULT_NAMES=-
      # - turn off debug option controlling request logging: --LOWKEY_DEBUG_REQUEST_LOG=false
      # - specify the name of the import file: --LOWKEY_IMPORT_LOCATION=/import/keyvault.json.hbs
      # - defining the value of {{host}} placeholders in the import: --LOWKEY_IMPORT_TEMPLATE_HOST=localhost
      # - defining the value of {{port}} placeholders in the import: --LOWKEY_IMPORT_TEMPLATE_PORT=8443
      # More details at: https://github.com/nagyesta/lowkey-vault/tree/main/lowkey-vault-app#startup-parameters
      LOWKEY_ARGS: >
        --server.port=8443
        --server.ssl.key-store-type=JKS
        --server.ssl.key-store=/config/cert.jks
        --server.ssl.key-store-password=password
        --LOWKEY_VAULT_NAMES=-
        --LOWKEY_DEBUG_REQUEST_LOG=true
        --LOWKEY_IMPORT_LOCATION=/import/keyvault.json.hbs
        --LOWKEY_IMPORT_TEMPLATE_HOST=localhost
        --LOWKEY_IMPORT_TEMPLATE_PORT=8443
  assumed-identity:
    container_name: docker-compose-assumed-identity
    image: nagyesta/assumed-identity:1.2.61
    ports:
      - "8080:8080"
    environment:
      # Set port number to the one we want to use on the host machine
      ASSUMED_ID_PORT: "8080"
volumes:
  # Create a volume, allowing us to share the backup file with the container by mounting it
  example-import:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "$PWD/local/lowkey/import"
  example-config:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "$PWD/local/lowkey/config"
