services:
  localstack:
    container_name: "localstack-main"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - ./local/localstack:/etc/localstack/init/ready.d
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  hashicorp-vault:
    container_name: "hashicorp-vault"
    image: hashicorp/vault:latest
    ports:
      - "8200:8200" # Vault API
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=dev-only-token
  postgres:
    container_name: "postgres"
    image: postgres:latest
    ports:
      - "5432:5432" # PostgreSQL
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./local/postgres:/docker-entrypoint-initdb.d
  vault-prepopulate:
    image: hashicorp/vault:latest
    depends_on:
      - hashicorp-vault
    volumes:
      - ./local/vault/init-vault.sh:/usr/local/bin/init-vault.sh
    command: ["sh", "-c", "/usr/local/bin/init-vault.sh"]
