name: Static Checks

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: Run Mage
        uses: magefile/mage-action@v3
        with:
          version: latest
          args: format:check
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: Start integration test containers
        run: docker compose up -d --build
      - name: Sleep for 30 seconds
        run: sleep 30
      - name: Run Tests
        uses: magefile/mage-action@v3
        with:
          version: latest
          args: test
